### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by tiny-pangolin** [mailcow/cow-app#1]
It has Come to my attention that a lot of the mailcow apps don't have a license. Is it possible to add one?

**Comment by afonsoingles** [comment]
2 years, and still nothing…

**Comment by MAGICCC** [comment]
I doubt this repo is active @afonsoingles

**Comment by andryyy** [comment]
I am trying to contact him on telegram. :)

**Comment by afonsoingles** [comment]
> I doubt this repo is active @afonsoingles 

me to...
